# Generated by Django 3.2.8 on 2021-10-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
