# Generated by Django 3.2.8 on 2021-10-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211025_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primage',
            field=models.ImageField(default='static/main/Dal.jpg', upload_to='upload_image'),
        ),
    ]
