# Generated by Django 3.2.8 on 2021-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_primage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='produ',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='primage',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
